### ISSUE TITLE
Out of Range Issue

### ISSUE THREAD

**Issue by neimex23** [neimex23/HitCounterManager#1]
### **Exception Produce:**
**System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index**
> at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewSelectedCellCollection.get_Item(Int32 index)
   at HitCounterManager.ProfileDataGridView.get_ActiveSplit()
   at HitCounterManager.ProfileDataGridView.AddDuration(Int64 Duration)
   at HitCounterManager.ProfilesControl.UpdateDuration()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**To Reproduce**
Randomly in DS3 when splits are more than splits events.

**Comment by neimex23** [comment]
Fixed in PR_3.2: Changing method of spliting.
